 
/**
 * Schema drift checker + fixture dumper.
 *
 * Fetches live devices from Daikin Cloud and reports any payload fields that
 * GatewayDeviceSchema would silently strip during Zod parsing. Stripped fields
 * are the same class of bug that caused HomeKit RotationSpeed to error out with
 * 400 INVALID_CHARACTERISTIC_VALUE: the schema dropped fanSpeed.modes.fixed's
 * minValue/maxValue/stepValue, setProps then ran with undefined ranges, and
 * HomeKit happily sent 0–100 percentages that Daikin rejects.
 *
 * Usage:
 *   npm run schema:check                     # diff only, uses test/hbConfig/config.json
 *   npm run schema:check -- --dump-fixtures  # also write fixtures to test/fixtures/live/
 *   npm run schema:check -- --config path/to/config.json --out-dir tmp/fixtures
 *
 * Exit codes: 0 = clean, 1 = drift found, 2 = setup/auth error.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { DaikinCloudController } from '../src/api/daikin-controller';
import { GatewayDeviceSchema } from '../src/api/daikin-schemas';

type CliArgs = {
    configPath: string;
    dumpFixtures: boolean;
    outDir: string;
};

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    configPath: 'test/hbConfig/config.json',
    dumpFixtures: false,
    outDir: 'test/fixtures/live',
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    switch (a) {
      case '--config': args.configPath = argv[++i]; break;
      case '--dump-fixtures': args.dumpFixtures = true; break;
      case '--out-dir': args.outDir = argv[++i]; break;
      case '--help':
      case '-h':
        console.log(
          'Usage: npm run schema:check -- [--config <path>] [--dump-fixtures] [--out-dir <dir>]',
        );
        process.exit(0);
        break;
      default:
        throw new Error(`Unknown arg: ${a}`);
    }
  }
  return args;
}

function loadPlatformConfig(configPath: string) {
  const cfg = JSON.parse(readFileSync(resolve(configPath), 'utf8')) as {
        platforms?: Array<Record<string, unknown>>;
    };
  const platform = cfg.platforms?.find(p => p.platform === 'DaikinCloud');
  if (!platform) {
    throw new Error(`No DaikinCloud platform block in ${configPath}`);
  }
  return platform as Record<string, unknown>;
}

/**
 * Walk raw + parsed in parallel and report every key Zod stripped. Returns
 * dotted paths (e.g. "managementPoints[1].fanControl.value.operationModes.cooling.fanSpeed.modes.fixed.minValue").
 */
function findStrippedKeys(raw: unknown, parsed: unknown, path = ''): string[] {
  if (raw === null || raw === undefined || typeof raw !== 'object') {
    return [];
  }
  if (parsed === null || parsed === undefined || typeof parsed !== 'object') {
    // Whole subtree was dropped (e.g. parent is undefined). Report it once.
    return path ? [path] : [];
  }
  if (Array.isArray(raw)) {
    if (!Array.isArray(parsed)) {
      return [];
    }
    return raw.flatMap((r, i) => findStrippedKeys(r, parsed[i], `${path}[${i}]`));
  }
  const out: string[] = [];
  for (const key of Object.keys(raw)) {
    const childPath = path ? `${path}.${key}` : key;
    if (!(key in (parsed as Record<string, unknown>))) {
      out.push(childPath);
    } else {
      out.push(...findStrippedKeys(
        (raw as Record<string, unknown>)[key],
        (parsed as Record<string, unknown>)[key],
        childPath,
      ));
    }
  }
  return out;
}

function slugify(name: string): string {
  return name.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'unnamed';
}

function pickFixtureBaseName(device: Record<string, unknown>): string {
  const mps = Array.isArray(device.managementPoints) ? device.managementPoints : [];
  const climate = mps.find((mp) => (mp as { embeddedId?: string })?.embeddedId === 'climateControl') as
        { name?: { value?: string } } | undefined;
  const friendly = climate?.name?.value || (device.deviceModel as string) || (device.id as string);
  const model = (device.deviceModel as string) || 'unknown';
  return `${slugify(friendly)}-${slugify(model)}`;
}

function toCamel(slug: string): string {
  return slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function writeFixture(outDir: string, device: Record<string, unknown>): string {
  mkdirSync(outDir, { recursive: true });
  const base = pickFixtureBaseName(device);
  const filePath = resolve(outDir, `${base}.ts`);
  const body =
        '// Live capture — generated by scripts/check-schema-drift.ts.\n' +
        '// Contains real device IDs; do NOT commit without scrubbing.\n' +
        `export const ${toCamel(base)} = ${JSON.stringify(device, null, 2)} as const;\n`;
  writeFileSync(filePath, body);
  return filePath;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const platform = loadPlatformConfig(args.configPath);

  const authMode = (platform.authMode as string) === 'mobile_app' ? 'mobile_app' : 'developer_portal';
  const storagePath = dirname(resolve(args.configPath));
  const tokenFileName = authMode === 'mobile_app'
    ? '.daikin-mobile-tokenset'
    : '.daikin-controller-cloud-tokenset';
  const tokenFilePath = resolve(storagePath, tokenFileName);

  const controllerConfig = {
    authMode,
    tokenFilePath,
    clientId: platform.clientId as string | undefined,
    clientSecret: platform.clientSecret as string | undefined,
    callbackServerExternalAddress: platform.callbackServerExternalAddress as string | undefined,
    callbackServerPort: (platform.callbackServerPort as number | undefined) || 8582,
    oidcCallbackServerBindAddr: platform.oidcCallbackServerBindAddr as string | undefined,
    email: platform.daikinEmail as string | undefined,
    password: platform.daikinPassword as string | undefined,
  };

  const controller = new DaikinCloudController(controllerConfig as never);
  controller.on('error', (msg: string) => console.error('[controller]', msg));
  controller.on('log', (msg: string) => console.log('[controller]', msg));

  if (!controller.isAuthenticated()) {
    if (authMode === 'mobile_app') {
      console.log('[auth] No cached token — authenticating with mobile credentials…');
      await controller.authenticateMobile();
    } else {
      console.error(
        'Not authenticated. For developer_portal mode, complete the OAuth flow via Homebridge UI first.',
      );
      process.exit(2);
    }
  }

  // The public API returns Zod-parsed data, which is exactly what we want to
  // diff against. We need both shapes, so we reach into the controller's
  // internal HTTP layer for the raw payload. Worth it for a dev script.
  const api = (controller as unknown as { api: { request: (p: string) => Promise<unknown> } }).api;
  const rawDevices = await api.request('/v1/gateway-devices') as Array<Record<string, unknown>>;

  console.log(`Fetched ${rawDevices.length} device(s).\n`);

  let driftCount = 0;
  for (const raw of rawDevices) {
    const parseResult = GatewayDeviceSchema.safeParse(raw);
    const label = `${pickFixtureBaseName(raw)} (${raw.id})`;

    if (!parseResult.success) {
      driftCount++;
      console.log(`❌ ${label}: schema VALIDATION FAILED`);
      for (const issue of parseResult.error.issues) {
        console.log(`    - ${issue.path.join('.')}: ${issue.message}`);
      }
    } else {
      const stripped = findStrippedKeys(raw, parseResult.data);
      if (stripped.length === 0) {
        console.log(`✅ ${label}: no schema drift`);
      } else {
        driftCount++;
        console.log(`⚠️  ${label}: ${stripped.length} field(s) silently stripped:`);
        for (const p of stripped) {
          console.log(`    - ${p}`);
        }
      }
    }

    if (args.dumpFixtures) {
      const filePath = writeFixture(args.outDir, raw);
      console.log(`   ↳ fixture: ${filePath}`);
    }
  }

  console.log('');
  if (driftCount === 0) {
    console.log('All devices parse cleanly with no stripped fields.');
    process.exit(0);
  }
  console.log(`Schema drift detected on ${driftCount} device(s). Update src/api/daikin-schemas.ts.`);
  process.exit(1);
}

main().catch((err) => {
  console.error('Fatal:', err instanceof Error ? err.stack ?? err.message : err);
  process.exit(2);
});
